# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53571837598fbfcd421c137680117e9b85df084d35bb4428bd41e57cb0fb7b5fdcfe63c874b86a2bc8191dd25953cdcd08cc93125d5e4d3ee8e09804d5483e6a

test:
  secret_key_base: bb96015e25797bc4308b0eab8fd85dc30f31e0dfbf00d0b7e042fb87fb8564de53379816d184bd90d6704a96ec060cc576526830bfaa42055e3e7b31faf3dba9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
